### ISSUE TITLE
How do I get the sqlserver server to read the local CSV file?

### ISSUE THREAD

**Issue by wuhuanyan** [cnstlungu/pd2mssql#1]
Hi, I've been using your code recently.

Note that the exported CSV files need to be imported on the sqlserver server.

I can upload files to the server first, or let the server access "UNC PATH".

But generally speaking, the application server is separate from the database server, and there are security restrictions.

So can you read the CSV file into the local memory and then import it?

**Comment by cnstlungu** [comment]
Hi @wuhuanyan .

Many thanks for your message.

Given the package is dependent on SQL Server Bulk insert, the CSV files needs to be either on the same machine as the SQL Server instance or at a network location accessible to it.

I am currently unaware of any way of overcoming this limitation.

Please also check this [link](https://stackoverflow.com/questions/29638136/how-to-speed-up-bulk-insert-to-ms-sql-server-from-csv-using-pyodbc/29649340#29649340) for further info.

Thanks
